### ISSUE TITLE
Fix Git hook (was: Update for Fedora 37 release & fix ppc64le links)

### ISSUE THREAD

**Issue by travier** [fedora-silverblue/silverblue-site#116]
See https://github.com/fedora-silverblue/silverblue-site/pull/115.

The update has not been deployed and the ppc64le links are broken.

**Comment by miabbott** [comment]
I reached out to folks in the Websites space (#websites:fedoraproject.org) on the Fedora Matrix instance and got the site rebuilt.  (Thanks to `darknao`!)

I was advised that the site is hosted on the Fedora OpenShift infra and there are only two people that are allowed to rebuild the site:  `misc` and `sanja`.  If we want to adjust the users that have that ability, we have to reach out to the Fedora Infra team.

Additionally, we could set up a GitHub webhook trigger to rebuilt the site on a new commit to this repo. That will also require coordination with Fedora Infra folks.

**Comment by travier** [comment]
Thanks @miabbott

**Comment by travier** [comment]
Hum, where is this Git hook configured? I don't have admin access here.

**Comment by miabbott** [comment]
> Hum, where is this Git hook configured? I don't have admin access here.

It's under Settings for this repo:

![image](https://user-images.githubusercontent.com/10236257/202717769-704e4af1-b191-400c-ae8e-ae3128c7049f.png)

I must have had admin rights given to me ages ago :shrug:

**Comment by tpopela** [comment]
@miabbott can you give @travier admin rights as well? I'm was trying to find out how to do it, but I failed badly :/

**Comment by miabbott** [comment]
I added @travier as an `Owner` in the top level membership for `fedora-silverblue` (https://github.com/orgs/fedora-silverblue/people)

**Comment by travier** [comment]
This is now fixed! Thanks @miabbott.
