### ISSUE TITLE
Mobile-friendly menu

### ISSUE THREAD

**Issue by matthiasclasen** [fedora-silverblue/silverblue-site#25]
On a phone screen, the horizontal orientation of the menu doesn't help. It ends up getting stacked vertically anyway. We need a popover solution in that case.

**Comment by mercyikpe** [comment]
Hello @matthiasclasen 

I recreated this issue in my browser and will like to contribute to solve this issue.
![image](https://user-images.githubusercontent.com/29842348/76254736-45b95880-624d-11ea-81c6-5a0b92b6e441.png)

**Comment by travier** [comment]
Thank for reporting this issue.

I'll close this issue as we've shifted focus for the Silverblue website to including it as part of the new official Fedora Project website at https://fedoraproject.org/silverblue/.

See this issue for more details: https://github.com/fedora-silverblue/silverblue-site/issues/114
