### ISSUE TITLE
Project Atomic Uses Immutable Infrastructure of  SilverBlue

### ISSUE THREAD

**Issue by Apollo9999** [fedora-silverblue/silverblue-site#37]
Atomic Host provides immutable infrastructure from TeamSilverBlue  for deploying to hundreds or thousands of servers in your private or public cloud. Available in Fedora Atomic Host, CentOS Atomic Host, and Red Hat Atomic Host editions depending on your platform and support needs.

To balance the need between long-term stability and new features, we are providing different releases of Atomic Host for you to choose from.

Atomic Host Images
Fedora Atomic Host is a leading edge base operating system following the Project Atomic model. It is designed around Kubernetes and containers. The images published here showcase that work. Note that the images have passed several levels of automated testing.

Please test before using new versions in production. If you do discover a problem, the Atomic Host tools make it easy to flip back to an earlier release — and if that happens, please also help us by filing bugs or submitting fixes.
Fedora Atomic Host images are updated roughly every two weeks, rather than on the main six-month Fedora cadence. Because development is moving quickly, only the latest major Fedora release is supported.
Note that different Fedora Atomic Host media are subject to different levels of automatic testing. You can learn more about the Atomic project at projectatomic.io. Click here to see the current test status.
Atomic Host Images for Amazon Public Cloud EC2
The links below will provide you listings of available Atomic Host Hardware Virtual Machine (HVM) AMIs by region with buttons to launch them in your Amazon Web Services account. AMI IDs for usage with the AWS Console or command-line tools are also provided.
GP2 Format HVM AMIs
Standard Format HVM AMIs

**Comment by Saurabh-Thakre** [comment]
@Apollo9999 Can't see it as a issue

**Comment by Lailah** [comment]
Neither I can. It makes sense to me that this is this way. Maybe I'm missing something?

**Comment by tpopela** [comment]
Closing, feel free to reopen the issue if you think it needs some attention.
