### ISSUE TITLE
Installation docs link doesn't work

### ISSUE THREAD

**Issue by stickster** [fedora-silverblue/silverblue-site#42]
The top link in Google for "installing silverblue" is https://docs.teamsilverblue.org/installing which yields a 404 (https://docs.fedoraproject.org/en-US/fedora-silverblue/installing). My guess is this is just a simple redirect that grafts the path to the new prefix.

Instead, the correct link is: https://docs.fedoraproject.org/en-US/fedora-silverblue/installation-guide/

**Comment by Saurabh-Thakre** [comment]
@stickster Would you please check it once if you see the same behaviour now ? as for me it seems the link has been updated correctly

**Comment by dyoungwd** [comment]
this is an old issue and can be closed

**Comment by Saurabh-Thakre** [comment]
Closing the issue as it has been resolved now.
