### ISSUE TITLE
Update for Silverblue 31

### ISSUE THREAD

**Issue by daizehnd** [fedora-silverblue/silverblue-site#74]
https://silverblue.fedoraproject.org/ and https://silverblue.fedoraproject.org/download need updates to reflect the release of Fedora 31.

**Comment by dustymabe** [comment]
thanks @daizehnd. @returntrip is working on this! Thanks @returntrip

**Comment by returntrip** [comment]
Actually It won't close this as we need also to update the frontpage. If someone has a small summary of improvements, I can add them.

**Comment by dustymabe** [comment]
> Actually It won't close this as we need also to update the frontpage. If someone has a small summary of improvements, I can add them.

for now we could just add a new Fedora 31 has been release section with links to the download page. I don't have specific things to add for highlights. Maybe @debarsiray would?

**Comment by returntrip** [comment]
FYA: @debarshiray

@dustymabe Here you go: https://github.com/fedora-silverblue/silverblue-site/pull/77

**Comment by debarshiray** [comment]
Thanks for working on this!

I just put out a Toolbox blog post:
https://debarshiray.wordpress.com/2019/11/01/toolbox-a-fall-2019-update/

There's also this Fedora Magazine article about Workstation 31, which also applies for Silverblue:
https://fedoramagazine.org/whats-new-fedora-31-workstation/

**Comment by returntrip** [comment]
Summary Proposal:

This release includes some exciting improvements, such as:

- Several `toolbox` [optimisations ](https://debarshiray.wordpress.com/2019/11/01/toolbox-a-fall-2019-update/) and tighter integrations with `libpod` (podman) and the host system
- GNOME being updated to version 3.34
- CgroupsV2 becoming our default control groups

If you guys believe the above is sufficient I can raise a PR.

**Comment by debarshiray** [comment]
Sounds good to me!
