### ISSUE TITLE
No control over dark mode

### ISSUE THREAD

**Issue by HarryMichal** [fedora-silverblue/silverblue-site#80]
The dark mode added by #73 is a handy feature but there is no option to toggle it off which may cause confusion (it did at least in my case :smile:).

**Comment by travier** [comment]
Thank for reporting this issue.

I'll close this issue as we've shifted focus for the Silverblue website to including it as part of the new official Fedora Project website at https://fedoraproject.org/silverblue/.

See this issue for more details: https://github.com/fedora-silverblue/silverblue-site/issues/114
