### ISSUE TITLE
Dead links for Fedora Media Writer

### ISSUE THREAD

**Issue by mikix** [fedora-silverblue/silverblue-site#84]
1. Visit https://silverblue.fedoraproject.org/download
2. Click `Fedora Media Writer for OS X` or `Fedora Media Writer for Windows` at the bottom.
3. See 404

I would expect those links to work.

(The Linux flatpak link does work.)

**Comment by mikix** [comment]
Specifically, at time of writing, those links go to:

https://getfedora.org/fmw/FedoraMediaWriter-osx-4.1.4.dmg
https://getfedora.org/fmw/FedoraMediaWriter-win32-4.1.4.exe

**Comment by masch** [comment]
Hi! I've created the #85 PR in order to fix them.
I get the same solution based on [getfedora.org pagure project](https://pagure.io/fedora-web/websites/blob/master/f/sites/getfedora.org/site/workstation/download/index.html#_67).

Please let me know if there is a better solution.

**Comment by tpopela** [comment]
Let me contact the FMW maintainers whether they could create a link that will always contain the latest version.
